### ISSUE TITLE
Special characters in URL don't turn out right

### ISSUE THREAD

**Issue by chris-h-sg** [ashafir20/node-google-text-to-speech#1]
Thanks for the example, this is working great!
I had some problems running this on node when there were special characters in the text, e.g. accented characters. Calling e.g. 'más' in Spanish works fine in my browser, but doesn't come out right here.

What I found is that for some strange reason, I had to set a User-Agent header in my node request, like so:

```
var r = request({uri: url, headers: {'User-Agent': 'Mozilla/5.0'}}, function (error, response, buffer) {
    ...
});
```

This  way, special characters turn out right just the way they do in the browser.

**Comment by avivshafir** [comment]
Thanks for replying.. I am currently not supporting this project..
